# compose.yaml

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ead-backend
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:docker@db:5432/revalida_postgres
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev

  db:
    image: postgres:16-alpine
    container_name: revalida_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: revalida_postgres
      PGDATA: /data/postgres
    volumes:
      - db-data:/data/postgres
      - ./logs/db:/var/log/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
