services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: prod

    container_name: ead-backend-prod
    env_file:
      - .env
    ports:
      - '${PORT:-3333}:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
