services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: prod

    container_name: ead-backend-prod
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
