# track.http
@BASE_URL = http://localhost:3333

### Create Track
POST {{BASE_URL}}/tracks
Content-Type: application/json

{
  "slug": "minha-trilha2",
 "imageUrl": "https://via.placeholder.com/600x400.png?text=Teste+de+Imagem",
  "courseIds": [
    "14f6baa1-7322-43db-a4a1-c3d004059a20"
  ],
  "translations": [
    {
      "locale": "pt",
      "title": "Trilha de Exemplo PT",
      "description": "Uma descrição em português para a trilha."
    },
    {
      "locale": "it",
      "title": "Traccia di Esempio IT",
      "description": "Una descrizione in italiano per la traccia."
    },
    {
      "locale": "es",
      "title": "Pista de Ejemplo ES",
      "description": "Una descripción en español para la pista."
    }
  ]
}

###ddb811e6-5420-439e-997a-426539784bae



GET {{BASE_URL}}/tracks/18bc95ce-6692-4071-a50e-59d3e3d28211
Content-Type: application/json


### List Tracks
GET {{BASE_URL}}/tracks
Content-Type: application/json