@BASE_URL = http://localhost:3333
# @BASE_URL = http://18.222.85.79:3333

###
# @name create-address
POST {{BASE_URL}}/addresses
Content-Type: application/json

{
  "userId":     "45348fe3-9683-4101-aaf2-e4483ffabcf5",
  "street":     "123 Main St",
  "number":     "42A",
  "complement": "Apt. 7",
  "district":   "Central",
  "city":       "Metropolis",
  "state":      "Stateville",
  "country":    "Freedonia",
  "postalCode": "12345-678"
}

###
# @name find-addresses-by-user
GET {{BASE_URL}}/addresses?userId=45348fe3-9683-4101-aaf2-e4483ffabcf5
Content-Type: application/json

###

###
# @name update-address
PATCH {{BASE_URL}}/addresses/fb33616b-8ca1-462e-a791-878fbe76dbb1
Content-Type: application/json

{
  "street":     "456 Elm St 2",
  "number":     "99B",
  "complement": "Suite 100",
  "district":   "New District",
  "city":       "New City",
  "state":      "New State",
  "country":    "New Country",
  "postalCode": "99999-999"
}

###
# @name delete-address
DELETE {{BASE_URL}}/addresses/fb33616b-8ca1-462e-a791-878fbe76dbb1
Content-Type: application/json