# requests/answer.http

@BASE_URL = http://localhost:3333
#@BASE_URL = http://18.216.107.74:3333
@contentType = application/json

### 1. Buscar Answer por ID - Sucesso
GET {{BASE_URL}}/answers/f5b59e4e-738c-400d-8735-c194b5598a86

### 2. Buscar Answer com traduções - Sucesso  
GET {{BASE_URL}}/answers/e2b59e4e-738c-400d-8735-c194b5598b92

### 3. Erro - ID inválido
GET {{BASE_URL}}/answers/invalid-uuid

### 4. Erro - Answer não encontrado
GET {{BASE_URL}}/answers/00000000-0000-0000-0000-000000000000

### 5. Teste de performance
GET {{BASE_URL}}/answers/f5b59e4e-738c-400d-8735-c194b5598a86