# requests/answer.http

@BASE_URL = http://localhost:3333
#@BASE_URL = http://18.216.107.74:3333
@contentType = application/json

### 1. Criar Answer - Sucesso (Question OPEN)
POST {{BASE_URL}}/answers
Content-Type: {{contentType}}

{
  "explanation": "A hipertensão arterial é caracterizada por pressão arterial elevada (≥140/90 mmHg).",
  "questionId": "550e8400-e29b-41d4-a716-446655440062",
  "translations": [
    {
      "locale": "pt",
      "explanation": "A hipertensão arterial é caracterizada por pressão arterial elevada (≥140/90 mmHg)."
    }
  ]
}

### 2. Criar Answer - Sucesso (Question MULTIPLE_CHOICE)
POST {{BASE_URL}}/answers
Content-Type: {{contentType}}

{
  "explanation": "Esta é a resposta correta para a questão de múltipla escolha.",
  "questionId": "550e8400-e29b-41d4-a716-446655440022",
  "correctOptionId": "550e8400-e29b-41d4-a716-446655440022-option-1",
  "translations": [
    {
      "locale": "pt",
      "explanation": "Esta é a resposta correta para a questão de múltipla escolha."
    },
    {
      "locale": "it",
      "explanation": "Questa è la risposta corretta per la domanda a scelta multipla."
    }
    {
      "locale": "es",
      "explanation": "Questa è la risposta corretta per la domanda a scelta multipla. em espanhol"
    }
  ]
}

### 3. Buscar Answer por ID - Sucesso
GET {{BASE_URL}}/answers/550e8400-e29b-41d4-a716-446655440023

### 4. Buscar Answer com traduções - Sucesso  
GET {{BASE_URL}}/answers/550e8400-e29b-41d4-a716-446655440053

### 5. Erro - ID inválido
GET {{BASE_URL}}/answers/invalid-uuid

### 6. Erro - Answer não encontrado
GET {{BASE_URL}}/answers/00000000-0000-0000-0000-000000000000

### 7. Listar Answers - Paginação padrão
GET {{BASE_URL}}/answers

### 8. Listar Answers - Com paginação customizada
GET {{BASE_URL}}/answers?page=1&limit=5

### 9. Listar Answers - Filtrar por questionId
GET {{BASE_URL}}/answers?questionId=550e8400-e29b-41d4-a716-446655440022

### 10. Listar Answers - Filtrar por questionId com paginação
GET {{BASE_URL}}/answers?page=2&limit=10&questionId=550e8400-e29b-41d4-a716-446655440062

### 11. Listar Answers - Limite máximo
GET {{BASE_URL}}/answers?limit=100

### 12. Erro - Page inválida
GET {{BASE_URL}}/answers?page=0&limit=10

### 13. Erro - Limit excedido
GET {{BASE_URL}}/answers?limit=101

### 14. Erro - Question ID inválido
GET {{BASE_URL}}/answers?questionId=invalid-uuid

### 15. Erro - Answer já existe
POST {{BASE_URL}}/answers
Content-Type: {{contentType}}

{
  "explanation": "Tentativa de criar answer duplicada",
  "questionId": "550e8400-e29b-41d4-a716-446655440022"
}