# requests/argument.http
@BASE_URL = http://localhost:3333


#@BASE_URL = http://18.216.107.74:3333

@contentType = application/json

### 1. Criar Argument com assessmentId - Sucesso
POST {{BASE_URL}}/arguments
Content-Type: {{contentType}}

{
  "title": "Anatomia Cardiovascular",
  "assessmentId": "a78d5558-6962-41de-911b-d8c12821b9b9"
}

### 2. Criar Argument sem assessmentId - Sucesso
POST {{BASE_URL}}/arguments
Content-Type: {{contentType}}

{
  "title": "Farmacologia 2"
}
### ==================== GET ARGUMENT REQUESTS ====================

### 26. GET - Buscar Argument por ID válido - Sucesso
GET {{BASE_URL}}/arguments/efcab69b-b421-4326-898f-3bbb2b0c9803
Content-Type: {{contentType}}



### 26. GET - Buscar Argument List
GET {{BASE_URL}}/arguments/
Content-Type: {{contentType}}

### ==================== UPDATE ARGUMENT REQUESTS ====================

### 51. PUT - Update argument title - Sucesso
PUT {{BASE_URL}}/arguments/eca4848c-07e4-49d0-b8b3-b26be563a4f4
Content-Type: {{contentType}}

{
  "title": "Título Atualizado para Anatomia Cardiovascular"
}

