#@BASE_URL = http://localhost:3333
@BASE_URL = http://3.131.246.201:3333

###
# @name create-account
POST {{BASE_URL}}/students
Content-Type: application/json

{
  "name": "Walter Bruno Prado Vieira",
  "email": "bruno@wbdigitalsolutions.com",
  "password": "Senha123!",
  "role": "student",
  "cpf": "12145678900"
}
###

###
# @name login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "bruno@wbdigitalsolutions.com",
  "password": "Senha123!"
}
###

###
# @name update-account
PATCH {{BASE_URL}}/students/b0997302-513c-4d6f-8fe5-502ccb9c859a
Content-Type: application/json

{
  "name": "Walter Bruno P. Vieira (Atualizado)",
  "email": "wbrunovieira53_atualizado@yahoo.com.br",
  "cpf": "12745678901",
  "role": "student"
}
###