# @BASE_URL = http://localhost:3333
@BASE_URL = http://18.222.85.79:3333"


###

# @name create-account
POST {{BASE_URL}}/students
Content-Type: application/json

{
  "name": "Walter Bruno Prado Vieira",
  "email": "wbrunovieira5@yahoo.com.br",
  "password":"123456aA@",
  "role":"student",
  "cpf":"12445678900"
}

###
# @name login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "wbrunovieira5@yahoo.com.br",
  "password": "123456aA@"
}
###

