@BASE_URL = http://localhost:3333
#@BASE_URL = http://18.216.107.74:3333

###
# @name create-course
POST {{BASE_URL}}/courses
Content-Type: application/json

{
  "slug": "curso-teste",
   "imageUrl": "/images/capa-track.avif",
  "translations": [
    {
      "locale": "pt",
      "title": "Titulo Curso pt",
      "description": "Descricao curso pt."
    },
    {
      "locale": "it",
      "title": "Titulo Curso it",
      "description": "Descricao curso it."
    },
    {
      "locale": "es",
      "title": "Titulo Curso pt",
      "description": "Descricao curso es."
    }
  ]
}

###

# @name list-courses
GET {{BASE_URL}}/courses
Content-Type: application/json

###

# @name get-course
GET {{BASE_URL}}/courses/04799601-bc16-4872-a2ff-91dc69b8d97a
Content-Type: application/json


### 
# @name delete-course-success
DELETE {{BASE_URL}}/courses/aa4fbdc7-a87f-4c18-a39c-fd7066289d8f
Content-Type: application/json




### 
# @name update-course-complete
PUT {{BASE_URL}}/courses/04799601-bc16-4872-a2ff-91dc69b8d97a
Content-Type: application/json

{
  "slug": "curso-atualizado-completo2ww2",
  "imageUrl": "/images/nova-capa.jpg",
  "translations": [
    {
      "locale": "pt",
      "title": "Curso Completamente Atualizado",
      "description": "Nova descrição do curso com todas as informações atualizadas."
    },
    {
      "locale": "it",
      "title": "Corso Completamente Aggiornato",
      "description": "Nuova descrizione del corso con tutte le informazioni aggiornate."
    },
    {
      "locale": "es",
      "title": "Curso Completamente Actualizado",
      "description": "Nueva descripción del curso con toda la información actualizada."
    }
  ]
}

