@BASE_URL = http://localhost:3333

###
# @name create-course
POST {{BASE_URL}}/courses
Content-Type: application/json

{
  "slug": "matematica-avancada",
  "translations": [
    {
      "locale": "pt",
      "title": "Matemática Avançada",
      "description": "Um mergulho profundo em tópicos avançados de matemática."
    },
    {
      "locale": "it",
      "title": "Matematica Avanzata",
      "description": "Un'immersione approfondita in argomenti matematici avanzati."
    },
    {
      "locale": "es",
      "title": "Matemáticas Avanzadas",
      "description": "Una inmersión profunda en temas avanzados de matemáticas."
    }
  ]
}

###

# @name list-courses
GET {{BASE_URL}}/courses
Content-Type: application/json

###

# @name get-course
GET {{BASE_URL}}/courses/307a3302-3910-44f6-ac95-28033a0569a9
Content-Type: application/json