@BASE_URL = http://localhost:3333

###
# @name create-course
POST {{BASE_URL}}/courses
Content-Type: application/json

{
  "slug": "matematica-avancada3",
   "imageUrl": "/images/capa-track.avif",
  "translations": [
    {
      "locale": "pt",
      "title": "Matemática Avançada3",
      "description": "Um mergulho profundo em tópicos avançados de matemática."
    },
    {
      "locale": "it",
      "title": "Matematica Avanzata3",
      "description": "Un'immersione approfondita in argomenti matematici avanzati."
    },
    {
      "locale": "es",
      "title": "Matemáticas Avanzadas3",
      "description": "Una inmersión profunda en temas avanzados de matemáticas."
    }
  ]
}

###

# @name list-courses
GET {{BASE_URL}}/courses
Content-Type: application/json

###

# @name get-course
GET {{BASE_URL}}/courses/1b183dde-064c-4d48-9bec-dacb8e4217e4
Content-Type: application/json