# Document HTTP Requests
@BASE_URL = http://localhost:3333

#@BASE_URL = http://18.216.107.74:3333
###
# @name create-document
POST {{BASE_URL}}/lessons/c6acfbda-2f43-43a5-a2db-0ed83eb5b8a0/documents
Content-Type: application/json

{
 
  "filename": "material-curso-derivadas.pdf",
  "fileSize": 2547890,
  "mimeType": "application/pdf",
  "isDownloadable": true,
  "translations": [
    {
      "locale": "pt",
      "title": "Material do Curso - Derivadas33",
      "description": "Apostila completa sobre cálculo diferencial e derivadas.pt",
      "url": "/document/urlemportugues."
    },
    {
      "locale": "it",
      "title": "Materiale del Corso - Derivate33",
       "description": "Apostila completa sobre cálculo diferencial e derivadas.it",
       "url": "/document/urlemitaliano."
    },
    {
      "locale": "es",
      "title": "Material del Curso - Derivadas333",
       "description": "Apostila completa sobre cálculo diferencial e derivadas. es",
      "url": "/document/urlemespanhol"
    }
  ]
}

###
# @name create-word-document
POST {{BASE_URL}}/courses/055e8884-abf4-4ae4-97dc-12809271ea6c/lessons/a16eb397-561a-499c-b2b3-aa1ae0231bfa/documents
Content-Type: application/json

{
  "url": "https://cdn.example.com/documents/exercicios-praticos.docx",
  "filename": "exercicios-praticos.docx",
  "fileSize": 1234567,
  "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "isDownloadable": true,
  "translations": [
    {
      "locale": "pt",
      "title": "Exercícios Práticos",
      "description": "Lista de exercícios para praticar os conceitos aprendidos."
    },
    {
      "locale": "it",
      "title": "Esercizi Pratici",
      "description": "Lista di esercizi per praticare i concetti appresi."
    },
    {
      "locale": "es",
      "title": "Ejercicios Prácticos",
      "description": "Lista de ejercicios para practicar los conceptos aprendidos."
    }
  ]
}

###
# @name create-excel-document
POST {{BASE_URL}}/courses/055e8884-abf4-4ae4-97dc-12809271ea6c/lessons/a16eb397-561a-499c-b2b3-aa1ae0231bfa/documents
Content-Type: application/json

{
  "url": "https://cdn.example.com/documents/planilha-calculos.xlsx",
  "filename": "planilha-calculos.xlsx",
  "fileSize": 892345,
  "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "isDownloadable": true,
  "translations": [
    {
      "locale": "pt",
      "title": "Planilha de Cálculos",
      "description": "Planilha Excel com exemplos de cálculos de derivadas."
    },
    {
      "locale": "it",
      "title": "Foglio di Calcolo",
      "description": "Foglio Excel con esempi di calcoli di derivate."
    },
    {
      "locale": "es",
      "title": "Hoja de Cálculo",
      "description": "Hoja Excel con ejemplos de cálculos de derivadas."
    }
  ]
}

### 
# @name get-document
GET {{BASE_URL}}/lessons/e936312a-d6f2-44d7-997d-4c6ea6066a6f/documents/ebd55495-9e38-4862-b4b6-e9e5af25d1d5
Accept: application/json

### 
# @name list-documents
GET {{BASE_URL}}/lessons/c6acfbda-2f43-43a5-a2db-0ed83eb5b8a0/documents
Accept: application/json

### 
# @name increment-download
POST {{BASE_URL}}/courses/055e8884-abf4-4ae4-97dc-12809271ea6c/lessons/a16eb397-561a-499c-b2b3-aa1ae0231bfa/documents/c3ed5a10-60b6-4a8c-8add-6770784a6553/download

###
# @name delete-document-success
DELETE {{BASE_URL}}/lessons/e936312a-d6f2-44d7-997d-4c6ea6066a6f/documents/432245df-0406-48bd-b852-5541df7b7e3e


###
# @name update-document-complete
PUT {{BASE_URL}}/lessons/e936312a-d6f2-44d7-997d-4c6ea6066a6f/documents/ebd55495-9e38-4862-b4b6-e9e5af25d1d5
Content-Type: application/json

{
  "filename": "material-curso-derivadas-v2.pdf",
  "fileSize": 3547890,
  "mimeType": "application/pdf",
  "isDownloadable": false,
  "translations": [
    {
      "locale": "pt",
      "title": "Material do Curso - Derivadas (Versão 2)",
      "description": "Apostila atualizada e expandida sobre cálculo diferencial e derivadas.",
      "url": "/document/v2/urlemportugues.pdf"
    },
    {
      "locale": "it",
      "title": "Materiale del Corso - Derivate (Versione 2)",
      "description": "Dispensa aggiornata ed espansa sul calcolo differenziale e derivate.",
      "url": "/document/v2/urlemitaliano.pdf"
    },
    {
      "locale": "es",
      "title": "Material del Curso - Derivadas (Versión 2)",
      "description": "Apostilla actualizada y expandida sobre cálculo diferencial y derivadas.",
      "url": "/document/v2/urlemespanhol.pdf"
    }
  ]
}

###
# @name update-document-partial-metadata
PUT {{BASE_URL}}/lessons/e936312a-d6f2-44d7-997d-4c6ea6066a6f/documents/432245df-0406-48bd-b852-5541df7b7e3e
Content-Type: application/json

{
  "filename": "material-curso-derivadas-revisado.pdf",
  "fileSize": 2847890
}
