
@BASE_URL = http://localhost:3333


### Create Lesson
POST {{BASE_URL}}/3788fa7b-e274-4fd6-8ca8-a8274067ba82/modules/6cab3e65-4e55-4169-aa94-5484ac078031/lessons
Content-Type: application/json

{
  "moduleId": "6cab3e65-4e55-4169-aa94-5484ac078031",
  "translations": [
    { "locale": "pt", "title": "Aula PT", "description": "Descrição PT" },
    { "locale": "it", "title": "Lezione IT", "description": "Descrizione IT" },
    { "locale": "es", "title": "Lección ES", "description": "Descripción ES" }
  ]
}