
@BASE_URL = http://localhost:3333


### Create Lesson
POST {{BASE_URL}}/courses/055e8884-abf4-4ae4-97dc-12809271ea6c/modules/379fb12e-efb4-4e1c-9239-c4bb03af20af/lessons
Content-Type: application/json

{
  "moduleId": "379fb12e-efb4-4e1c-9239-c4bb03af20af",
  "translations": [
    { "locale": "pt", "title": "Aula PT", "description": "Descrição PT" },
    { "locale": "it", "title": "Lezione IT", "description": "Descrizione IT" },
    { "locale": "es", "title": "Lección ES", "description": "Descripción ES" }
  ]
}