
@BASE_URL = http://localhost:3333


### Create Lesson
POST {{BASE_URL}}/courses/1b183dde-064c-4d48-9bec-dacb8e4217e4/modules/c1542c84-49b8-4787-807b-97d9a36caa72/lessons
Content-Type: application/json

{
  "moduleId": "c1542c84-49b8-4787-807b-97d9a36caa72",
   "imageUrl": "/images/capa-track.avif",
  "translations": [
    { "locale": "pt", "title": "Aula PT", "description": "Descrição PT" },
    { "locale": "it", "title": "Lezione IT", "description": "Descrizione IT" },
    { "locale": "es", "title": "Lección ES", "description": "Descripción ES" }
  ]
}


### Create Lesson (with video)
POST {{BASE_URL}}/courses/1fc39af9-534a-4020-bc6d-3f7f1c8dda90/modules/b4998d32-12b6-40e2-88eb-6c02c0f15333/lessons
Content-Type: application/json

{
  "videoId": "2683acb4-477e-4509-ad61-58ff06665394",
  "translations": [
    { "locale": "pt", "title": "Aula com Vídeo PT", "description": "Descrição PT" },
    { "locale": "it", "title": "Lezione con Video IT", "description": "Descrizione IT" },
    { "locale": "es", "title": "Lección con Video ES", "description": "Descripción ES" }
  ]
}


### List Lessons
GET {{BASE_URL}}/courses/1b183dde-064c-4d48-9bec-dacb8e4217e4/modules/c1542c84-49b8-4787-807b-97d9a36caa72/lessons