@BASE_URL = http://localhost:3333

###
# @name create-module
POST {{BASE_URL}}/courses/1b183dde-064c-4d48-9bec-dacb8e4217e4/modules
Content-Type: application/json

{
  "slug": "modulo-calculo5",
   "imageUrl": "/images/capa-track.avif",
  "translations": [
    {
      "locale": "pt",
      "title": "Módulo Cálculo5",
      "description": "Introdução ao cálculo diferencial."
    },
    {
      "locale": "it",
      "title": "Modulo Calcolo5",
      "description": "Introduzione al calcolo differenziale."
    },
    {
      "locale": "es",
      "title": "Módulo Cálculo5",
      "description": "Introducción al cálculo diferencial."
    }
  ],
  "order": 6
}

###

# @name list-modules
GET {{BASE_URL}}/courses/1b183dde-064c-4d48-9bec-dacb8e4217e4/modules
Content-Type: application/json

###
# @name get-module
GET {{BASE_URL}}/courses/1b183dde-064c-4d48-9bec-dacb8e4217e4/modules/c1542c84-49b8-4787-807b-97d9a36caa72
Content-Type: application/json