@BASE_URL = http://localhost:3333

###
# @name create-module
POST {{BASE_URL}}/courses/055e8884-abf4-4ae4-97dc-12809271ea6c/modules
Content-Type: application/json

{
  "slug": "modulo-calculo2",
  "translations": [
    {
      "locale": "pt",
      "title": "Módulo Cálculo2",
      "description": "Introdução ao cálculo diferencial."
    },
    {
      "locale": "it",
      "title": "Modulo Calcolo2",
      "description": "Introduzione al calcolo differenziale."
    },
    {
      "locale": "es",
      "title": "Módulo Cálculo2",
      "description": "Introducción al cálculo diferencial."
    }
  ],
  "order": 2
}

###

# @name list-modules
GET {{BASE_URL}}/courses/055e8884-abf4-4ae4-97dc-12809271ea6c/modules
Content-Type: application/json

###
# @name get-module
GET {{BASE_URL}}/courses/4e5a55db-40d0-4e6a-bbe4-c6bb5061666d/modules/d7a19ec3-f094-4f9b-84e5-990f42dcb55a
Content-Type: application/json