@BASE_URL = http://localhost:3333
#@BASE_URL = http://18.216.107.74:3333

###
# @name create-module
POST {{BASE_URL}}/courses/1dddd700-2a21-4817-b237-02a60442b28e/modules
Content-Type: application/json

{
  "slug": "modulo-calculo",
   "imageUrl": "/images/capa-track.avif",
  "translations": [
    {
      "locale": "pt",
      "title": "Módulo Cálculo",
      "description": "Introdução ao cálculo diferencial."
    },
    {
      "locale": "it",
      "title": "Modulo Calcolo",
      "description": "Introduzione al calcolo differenziale."
    },
    {
      "locale": "es",
      "title": "Módulo Cálculo",
      "description": "Introducción al cálculo diferencial."
    }
  ],
  "order": 1
}

###

# @name list-modules
GET {{BASE_URL}}/courses/366daab0-ce1f-49ab-ac90-f83500ae3868/modules
Content-Type: application/json

###
# @name get-module
GET {{BASE_URL}}/courses/04799601-bc16-4872-a2ff-91dc69b8d97a/modules/64436979-2173-4518-be2f-6415961d9cef
Content-Type: application/json


###
# @name delete-module
DELETE {{BASE_URL}}/courses/fbe18d9c-a3c6-4799-9d64-b024d39813f8/modules/554d257b-1b37-40ce-9a2c-4240be4be4ac
Content-Type: application/json

###
# @name delete-module-with-dependencies
# Este exemplo testa a exclusão de um módulo que tem dependências (deve retornar erro 409)
DELETE {{BASE_URL}}/courses/fbe18d9c-a3c6-4799-9d64-b024d39813f8/modules/module-id-with-dependencies
Content-Type: application/json



###
# @name update-module
PATCH {{BASE_URL}}/courses/fbe18d9c-a3c6-4799-9d64-b024d39813f8/modules/884486b1-9488-4a2b-8095-6e05ad59e8e9
Content-Type: application/json

{
  "slug": "modulo-calculo-atualizado",
  "order": 8
}

###
# @name update-module-full
# Exemplo atualizando todos os campos
PATCH {{BASE_URL}}/courses/04799601-bc16-4872-a2ff-91dc69b8d97a/modules/64436979-2173-4518-be2f-6415961d9cef
Content-Type: application/json

{
  "slug": "modulo-completo-atualizado",
  "imageUrl": "/images/capa-track.avif",
  "translations": [
    {
      "locale": "pt",
      "title": "Módulo Atualizado",
      "description": "Nova descrição em português."
    },
    {
      "locale": "it",
      "title": "Modulo Aggiornato",
      "description": "Nuova descrizione in italiano."
    },
    {
      "locale": "es",
      "title": "Módulo Actualizado",
      "description": "Nueva descripción en español."
    }
  ],
  "order": 10
}

###
# @name update-module-remove-image
# Remove a imagem do módulo
PATCH {{BASE_URL}}/courses/fbe18d9c-a3c6-4799-9d64-b024d39813f8/modules/884486b1-9488-4a2b-8095-6e05ad59e8e9
Content-Type: application/json

{
  "imageUrl": null
}

###
# @name update-module-only-translations
# Atualiza apenas as traduções
PATCH {{BASE_URL}}/courses/fbe18d9c-a3c6-4799-9d64-b024d39813f8/modules/884486b1-9488-4a2b-8095-6e05ad59e8e9
Content-Type: application/json

{
  "translations": [
    {
      "locale": "pt",
      "title": "Novo Título PT",
      "description": "Nova descrição PT."
    },
    {
      "locale": "it",
      "title": "Nuovo Titolo IT",
      "description": "Nuova descrizione IT."
    },
    {
      "locale": "es",
      "title": "Nuevo Título ES",
      "description": "Nueva descripción ES."
    }
  ]
}
