@BASE_URL = http://localhost:3333

###
# @name create-video
POST {{BASE_URL}}/courses/055e8884-abf4-4ae4-97dc-12809271ea6c/lessons/a16eb397-561a-499c-b2b3-aa1ae0231bfa/videos
Content-Type: application/json

{
  "slug": "intro-derivadas",
  "providerVideoId": "5cbf2ba5-49e0-4319-8dd4-8944808fab5a",
  "translations": [
    {
      "locale": "pt",
      "title": "Introdução às Derivadas",
      "description": "Vídeo sobre os conceitos básicos de derivadas."
    },
    {
      "locale": "it",
      "title": "Introduzione alle Derivate",
      "description": "Video sui concetti di base delle derivate."
    },
    {
      "locale": "es",
      "title": "Introducción a las Derivadas",
      "description": "Vídeo sobre los conceptos básicos de derivadas."
    }
  ]
}

### get-video
GET {{BASE_URL}}/courses/055e8884-abf4-4ae4-97dc-12809271ea6c/modules/5e0e2e06-a74e-4553-ab9e-d1925be934e5/videos/c3ed5a10-60b6-4a8c-8add-6770784a6553
Accept: application/json

### list-videos
GET http://localhost:3333/courses/055e8884-abf4-4ae4-97dc-12809271ea6c/lessons/22fae576-4bfd-41e9-83ee-3a32e82357d6/videos
Accept: application/json