@BASE_URL = http://localhost:3333

###
# @name create-video
POST {{BASE_URL}}/courses/3788fa7b-e274-4fd6-8ca8-a8274067ba82/videos
Content-Type: application/json

{
  "slug": "intro-derivadas4",
  "providerVideoId": "5cbf2ba5-49e0-4319-8dd4-8944808fab5a",
  "translations": [
    {
      "locale": "pt",
      "title": "Introdução às Derivadas",
      "description": "Vídeo sobre os conceitos básicos de derivadas."
    },
    {
      "locale": "it",
      "title": "Introduzione alle Derivate",
      "description": "Video sui concetti di base delle derivate."
    },
    {
      "locale": "es",
      "title": "Introducción a las Derivadas",
      "description": "Vídeo sobre los conceptos básicos de derivadas."
    }
  ]
}

### get-video
GET {{BASE_URL}}/courses/75cd5469-0047-4402-8360-e6288ef6cd66/modules/5e0e2e06-a74e-4553-ab9e-d1925be934e5/videos/c3ed5a10-60b6-4a8c-8add-6770784a6553
Accept: application/json

### list-videos
GET {{BASE_URL}}/courses/75cd5469-0047-4402-8360-e6288ef6cd66/modules/5e0e2e06-a74e-4553-ab9e-d1925be934e5/videos
Accept: application/json